# Generated by Django 3.2.13 on 2023-09-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multipage_form', '0001_initial'),
        ('vr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinanpetltd',
            name='id',
        ),
        migrations.AddField(
            model_name='vinanpetltd',
            name='multipagemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multipage_form.multipagemodel'),
            preserve_default=False,
        ),
    ]
