# Generated by Django 3.2.13 on 2023-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0002_auto_20230915_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='aGO_Tank_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='aGO_Tank_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='aGO_Tank_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='dPK_Tank_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='dPK_Tank_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='dPK_Tank_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_1_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_1_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_1_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2a_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2a_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2a_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2b_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2b_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2b_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3a_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3a_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3a_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3b_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3b_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3b_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1a_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1a_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1a_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1b_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1b_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1b_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2a_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2a_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2a_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2b_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2b_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2b_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_3_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_3_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_3_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_4_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_4_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_4_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_5_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_5_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_5_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_6_Closing',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_6_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_6_Opening',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
