# Generated by Django 3.2.13 on 2023-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0004_auto_20230915_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_5_Difference',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
