# Generated by Django 3.2.13 on 2023-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0005_alter_vinanpetltd_pump_5_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Opening',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, null=True),
        ),
    ]
