# Generated by Django 3.2.13 on 2023-09-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0007_alter_vinanpetltd_tank_1_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='aGO_Tank_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='aGO_Tank_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='aGO_Tank_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='amount_Deposited',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vr.branch'),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='dPK_Tank_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='dPK_Tank_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='dPK_Tank_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='entry_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vr.product'),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_10_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_10_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_10_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_11_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_11_Difference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_11_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_12_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_12_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_12_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_1_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_1_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_1_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2a_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2a_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2a_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2b_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2b_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_2b_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3a_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3a_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3a_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3b_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3b_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_3b_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4a_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4a_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4a_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4b_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4b_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_4b_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_5_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_5_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_5_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_6_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_6_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_6_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_7_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_7_Difference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_7_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_8_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_8_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_8_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_9_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_9_Difference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='pump_9_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1a_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1a_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1a_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1b_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1b_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_1b_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2a_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2a_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2a_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2b_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2b_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_2b_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_3_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_3_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_3_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_4_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_4_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_4_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_5_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_5_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_5_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_6_Closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_6_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='tank_6_Opening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='teller',
            field=models.ImageField(blank=True, null=True, upload_to='teller'),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='teller_ID',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='total_Pump_Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
