# Generated by Django 3.2.13 on 2023-09-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0008_auto_20230916_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinanpetltd',
            old_name='amount',
            new_name='expected_Cash',
        ),
        migrations.RemoveField(
            model_name='vinanpetltd',
            name='amount_Deposited',
        ),
        migrations.RemoveField(
            model_name='vinanpetltd',
            name='cash',
        ),
    ]
