# Generated by Django 3.2.13 on 2023-09-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0010_vinanpetltdaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VinanPetLtdAccount',
        ),
    ]
