# Generated by Django 3.2.13 on 2023-10-02 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0011_delete_vinanpetltdaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='transaction_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
