# Generated by Django 3.2.13 on 2023-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0012_alter_vinanpetltd_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='entry_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='transaction_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
