# Generated by Django 3.2.13 on 2023-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0013_auto_20231002_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='entry_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vinanpetltd',
            name='transaction_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
