# Generated by Django 3.2.13 on 2023-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0014_auto_20231002_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='entry_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
