# Generated by Django 3.2.13 on 2023-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0015_alter_vinanpetltd_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinanpetltd',
            name='entry_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
